# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 89f7846d2954952d05fc84097926a14a9ff3927c6a0b30a598ee64257289ac73fb186302ffacf4e4b6ac5e2308d2787271dd8311fb07e3aff0299764440fc90b

test:
  secret_key_base: 9b3100d7cfe680bd74ef0806cd25d85663e621be866055606d66686f37e0fa5552b00d53fa0fd800ba6771b85eeef83214cb9d67b11c4a142a1483e9d446d276

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
